### ISSUE TITLE
Uncaught ReferenceError: Stripe is not defined

### ISSUE THREAD

**Issue by micahalcorn** [tyler-johnson/stripe-meteor#42] opened 2015-10-16 00:48 UTC
This error is getting thrown in my client code according to Kadira. I can't reproduce it from a desktop browser and it only seems to happen on Android. The culprit is my `Stripe.publishableKey = function...` inside of `Meteor.startup`. Are you aware of any issues with Meteor not properly waiting for the package to be loaded before running the startup function?

**Comment by wiserweb** [comment] 2015-10-21 23:16
Same issue here. "Uncaught ReferenceError: Stripe is not defined" occurring on Android devices.

The Stripe package works fine on web browser locally and remotely deployed. The error only appears to occur on Android device deployment.

 Stripe.setPublishableKey is being called in Meteor.startup on Client.

**Comment by wiserweb** [comment] 2015-10-22 01:35
This issue appears to be caused by new Cordova security rulesets.
The fix is to add the following line in mobile-config.js in the root of your meteor project.

App.accessRule("https://*.stripe.com/*")

**Comment by tyler-johnson** [comment] 2015-10-22 18:27
Hi, I've merged that updated documentation. Thanks!

**Closed by tyler-johnson** 2015-10-22 18:27 UTC
